import { PaddockDataBySector } from '@/lib/definitions';

// Array with user data for seeding
export const users = [
  {
    id: '8d451e49-4a1c-4c43-b6e1-96a85c5b4bd1',
    name: 'La Esmeralda',
    email: 'esmeralda@admin.com',
    password: 'Esm3ralda_Adm1n!2025',
  },
];

export const rotations = [
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442a',
    cattle_group: 'Vacas Cría 1',
    origin_pasture: 'Potrero Sur',
    destination_pasture: 'Potrero Norte',
    rotation_date: '2025-03-23',
    days_in_pasture: 5,
    observations: 'Rotación programada',
  },
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442b',
    cattle_group: 'Novillos A',
    origin_pasture: 'Potrero Norte',
    destination_pasture: 'Potrero Este',
    rotation_date: '2025-03-21',
    days_in_pasture: 24,
    observations: 'Pasto agotado',
  },
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442c',
    cattle_group: 'Terneros 2023',
    origin_pasture: 'Potrero Este',
    destination_pasture: 'Potrero Oeste',
    rotation_date: '2025-03-19',
    days_in_pasture: 13,
    observations: 'Rotación normal',
  },
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442d',
    cattle_group: 'Vaquillas',
    origin_pasture: 'Potrero Oeste',
    destination_pasture: 'Potrero Central',
    rotation_date: '2025-03-17',
    days_in_pasture: 23,
    observations: 'Rotación por falta de agua',
  },
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442e',
    cattle_group: 'Toros',
    origin_pasture: 'Potrero Central',
    destination_pasture: 'Potrero Sur',
    rotation_date: '2025-03-15',
    days_in_pasture: 16,
    observations: 'Rotación urgente',
  },
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442f',
    cattle_group: 'Vacas Cría 2',
    origin_pasture: 'Potrero Sur',
    destination_pasture: 'Potrero Norte',
    rotation_date: '2025-03-13',
    days_in_pasture: 8,
    observations: 'Descanso de potrero',
  },
  {
    id: '4058dc9e-712f-4377-85e9-fec4b6a64420',
    cattle_group: 'Novillos B',
    origin_pasture: 'Potrero Norte',
    destination_pasture: 'Potrero Este',
    rotation_date: '2025-03-11',
    days_in_pasture: 21,
    observations: 'Pasto agotado',
  },
  {
    id: '4158dc9e-712f-4377-85e9-fec4b6a64421',
    cattle_group: 'Terneros 2022',
    origin_pasture: 'Potrero Este',
    destination_pasture: 'Potrero Oeste',
    rotation_date: '2025-03-09',
    days_in_pasture: 26,
    observations: 'Rotación programada',
  },
  {
    id: '4258dc9e-712f-4377-85e9-fec4b6a64422',
    cattle_group: 'Vaquillas Jóvenes',
    origin_pasture: 'Potrero Oeste',
    destination_pasture: 'Potrero Central',
    rotation_date: '2025-03-07',
    days_in_pasture: 23,
    observations: 'Rotación urgente',
  },
  {
    id: '4358dc9e-712f-4377-85e9-fec4b6a64423',
    cattle_group: 'Vacas Lecheras',
    origin_pasture: 'Potrero Central',
    destination_pasture: 'Potrero Sur',
    rotation_date: '2025-03-05',
    days_in_pasture: 28,
    observations: 'Rotación por falta de agua',
  },
  {
    id: '4458dc9e-712f-4377-85e9-fec4b6a64424',
    cattle_group: 'Vacas Cría 1',
    origin_pasture: 'Potrero Sur',
    destination_pasture: 'Potrero Norte',
    rotation_date: '2025-03-03',
    days_in_pasture: 31,
    observations: 'Rotación urgente',
  },
  {
    id: '4558dc9e-712f-4377-85e9-fec4b6a64425',
    cattle_group: 'Novillos A',
    origin_pasture: 'Potrero Norte',
    destination_pasture: 'Potrero Este',
    rotation_date: '2025-03-01',
    days_in_pasture: 10,
    observations: 'Descanso de potrero',
  },
  {
    id: '4658dc9e-712f-4377-85e9-fec4b6a64426',
    cattle_group: 'Terneros 2023',
    origin_pasture: 'Potrero Este',
    destination_pasture: 'Potrero Oeste',
    rotation_date: '2025-02-27',
    days_in_pasture: 33,
    observations: 'Rotación por falta de agua',
  },
  {
    id: '4758dc9e-712f-4377-85e9-fec4b6a64427',
    cattle_group: 'Vaquillas',
    origin_pasture: 'Potrero Oeste',
    destination_pasture: 'Potrero Central',
    rotation_date: '2025-02-25',
    days_in_pasture: 34,
    observations: 'Pasto agotado',
  },
  {
    id: '4858dc9e-712f-4377-85e9-fec4b6a64428',
    cattle_group: 'Toros',
    origin_pasture: 'Potrero Central',
    destination_pasture: 'Potrero Sur',
    rotation_date: '2025-02-23',
    days_in_pasture: 35,
    observations: 'Rotación urgente',
  },
  {
    id: '4958dc9e-712f-4377-85e9-fec4b6a64429',
    cattle_group: 'Vacas Cría 2',
    origin_pasture: 'Potrero Sur',
    destination_pasture: 'Potrero Norte',
    rotation_date: '2025-02-21',
    days_in_pasture: 36,
    observations: 'Rotación programada',
  },
  {
    id: '5058dc9e-712f-4377-85e9-fec4b6a6442a',
    cattle_group: 'Novillos B',
    origin_pasture: 'Potrero Norte',
    destination_pasture: 'Potrero Este',
    rotation_date: '2025-02-19',
    days_in_pasture: 37,
    observations: 'Rotación urgente',
  },
  {
    id: '5158dc9e-712f-4377-85e9-fec4b6a6442b',
    cattle_group: 'Terneros 2022',
    origin_pasture: 'Potrero Este',
    destination_pasture: 'Potrero Oeste',
    rotation_date: '2025-02-17',
    days_in_pasture: 38,
    observations: 'Pasto agotado',
  },
  {
    id: '5258dc9e-712f-4377-85e9-fec4b6a6442c',
    cattle_group: 'Vaquillas Jóvenes',
    origin_pasture: 'Potrero Oeste',
    destination_pasture: 'Potrero Central',
    rotation_date: '2025-02-15',
    days_in_pasture: 39,
    observations: 'Rotación por falta de agua',
  },
  {
    id: '5358dc9e-712f-4377-85e9-fec4b6a6442d',
    cattle_group: 'Vacas Lecheras',
    origin_pasture: 'Potrero Central',
    destination_pasture: 'Potrero Sur',
    rotation_date: '2025-02-13',
    days_in_pasture: 40,
    observations: 'Rotación urgente',
  },
];

// Mock data for paddocks
export const paddockData: PaddockDataBySector = {
  A: [
    {
      id: 'A1',
      status: 'active',
      grassHeight: 85,
      area: 8.5,
      cattleCount: 15,
      daysLeft: 3,
    },
    {
      id: 'A2',
      status: 'vacant',
      grassHeight: 75,
      area: 7.2,
      recoveryRate: '+2%',
      readyIn: 0,
    },
    {
      id: 'A3',
      status: 'recovery',
      grassHeight: 40,
      area: 9.1,
      recoveryRate: '+5%',
      readyIn: 7,
    },
    {
      id: 'A4',
      status: 'vacant',
      grassHeight: 80,
      area: 6.8,
      recoveryRate: 'estable',
      readyIn: 0,
    },
    {
      id: 'A5',
      status: 'recovery',
      grassHeight: 45,
      area: 8.9,
      recoveryRate: '+3%',
      readyIn: 5,
    },
    {
      id: 'A6',
      status: 'vacant',
      grassHeight: 70,
      area: 7.5,
      recoveryRate: '+1%',
      readyIn: 0,
    },
    {
      id: 'A7',
      status: 'active',
      grassHeight: 75,
      area: 8.3,
      cattleCount: 12,
      daysLeft: 2,
    },
    {
      id: 'A8',
      status: 'recovery',
      grassHeight: 35,
      area: 6.7,
      recoveryRate: '+4%',
      readyIn: 8,
    },
  ],
  B: [
    {
      id: 'B1',
      status: 'recovery',
      grassHeight: 45,
      area: 7.8,
      recoveryRate: '+3%',
      readyIn: 6,
    },
    {
      id: 'B2',
      status: 'vacant',
      grassHeight: 80,
      area: 8.4,
      recoveryRate: 'estable',
      readyIn: 0,
    },
    {
      id: 'B3',
      status: 'active',
      grassHeight: 70,
      area: 9.2,
      cattleCount: 18,
      daysLeft: 4,
    },
    {
      id: 'B4',
      status: 'vacant',
      grassHeight: 75,
      area: 7.1,
      recoveryRate: '+1%',
      readyIn: 0,
    },
    {
      id: 'B5',
      status: 'recovery',
      grassHeight: 40,
      area: 8.7,
      recoveryRate: '+4%',
      readyIn: 7,
    },
    {
      id: 'B6',
      status: 'vacant',
      grassHeight: 85,
      area: 6.9,
      recoveryRate: 'estable',
      readyIn: 0,
    },
    {
      id: 'B7',
      status: 'recovery',
      grassHeight: 50,
      area: 7.5,
      recoveryRate: '+2%',
      readyIn: 5,
    },
    {
      id: 'B8',
      status: 'active',
      grassHeight: 75,
      area: 8.1,
      cattleCount: 14,
      daysLeft: 3,
    },
  ],
  C: [
    {
      id: 'C1',
      status: 'active',
      grassHeight: 75,
      area: 8.8,
      cattleCount: 16,
      daysLeft: 2,
    },
    {
      id: 'C2',
      status: 'vacant',
      grassHeight: 80,
      area: 7.6,
      recoveryRate: 'estable',
      readyIn: 0,
    },
    {
      id: 'C3',
      status: 'recovery',
      grassHeight: 45,
      area: 9.3,
      recoveryRate: '+3%',
      readyIn: 6,
    },
    {
      id: 'C4',
      status: 'vacant',
      grassHeight: 75,
      area: 6.5,
      recoveryRate: '+1%',
      readyIn: 0,
    },
    {
      id: 'C5',
      status: 'recovery',
      grassHeight: 40,
      area: 8.2,
      recoveryRate: '+4%',
      readyIn: 7,
    },
    {
      id: 'C6',
      status: 'vacant',
      grassHeight: 85,
      area: 7.7,
      recoveryRate: 'estable',
      readyIn: 0,
    },
    {
      id: 'C7',
      status: 'active',
      grassHeight: 70,
      area: 9.0,
      cattleCount: 15,
      daysLeft: 4,
    },
    {
      id: 'C8',
      status: 'recovery',
      grassHeight: 50,
      area: 7.3,
      recoveryRate: '+2%',
      readyIn: 5,
    },
  ],
  D: [
    {
      id: 'D1',
      status: 'vacant',
      grassHeight: 80,
      area: 8.6,
      recoveryRate: 'estable',
      readyIn: 0,
    },
    {
      id: 'D2',
      status: 'recovery',
      grassHeight: 45,
      area: 7.9,
      recoveryRate: '+3%',
      readyIn: 6,
    },
    {
      id: 'D3',
      status: 'vacant',
      grassHeight: 75,
      area: 8.5,
      recoveryRate: '+1%',
      readyIn: 0,
    },
    {
      id: 'D4',
      status: 'active',
      grassHeight: 70,
      area: 9.4,
      cattleCount: 17,
      daysLeft: 3,
    },
    {
      id: 'D5',
      status: 'recovery',
      grassHeight: 40,
      area: 7.2,
      recoveryRate: '+4%',
      readyIn: 7,
    },
    {
      id: 'D6',
      status: 'vacant',
      grassHeight: 85,
      area: 8.0,
      recoveryRate: 'estable',
      readyIn: 0,
    },
    {
      id: 'D7',
      status: 'active',
      grassHeight: 75,
      area: 7.4,
      cattleCount: 13,
      daysLeft: 2,
    },
    {
      id: 'D8',
      status: 'recovery',
      grassHeight: 50,
      area: 8.9,
      recoveryRate: '+2%',
      readyIn: 5,
    },
  ],
};
